<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit73a0a0a786556e8a0c6ca9235b795021
{
    public static $prefixLengthsPsr4 = array (
        'm' => 
        array (
            'monPotager\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'monPotager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit73a0a0a786556e8a0c6ca9235b795021::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit73a0a0a786556e8a0c6ca9235b795021::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit73a0a0a786556e8a0c6ca9235b795021::$classMap;

        }, null, ClassLoader::class);
    }
}
